### ISSUE TITLE
How to correctly setup Dropdown menu ?

### ISSUE THREAD

**Issue by ClementVidal** [samvloeberghs/foundation-sites-typings#1]
Hello !

I'm using a **drop down menu** in my application.
I setup this drop down with: 
`var dd = new Foundation.DropdownMenu(myDropDownMenu);`
(_like specified in the [foundation doc about drop down menu](http://foundation.zurb.com/sites/docs/dropdown-menu.html)_)

Everything work fine with that, the drop down work, but with your typescript definition, i get the following typescript errors:
`error TS2350: Only a void function can be called with the 'new' keyword.`

I'm using:
_tsc: 1.7.5
foundation-sites: 6.2.1_

Any idea about how to solve that ?

Thanks a lot !

**Comment by samvloeberghs** [comment]
Hi, I need to push an update, but am in need of time desperatly. Can't promise it to be quick , but have time scheduled by the end of next week to do the updates.

**Comment by ClementVidal** [comment]
If you give some hints about how to do that, i would be glad to do it and submit a pr.

**Comment by samvloeberghs** [comment]
I would start with the TS2350 error as well, don't know by heart what to do.
Please be aware that these typings are for 6.1

**Comment by samvloeberghs** [comment]
I thought this commit handled that BTW:

If I check
https://github.com/samvloeberghs/foundation-sites-typings/commit/57a91b4a8ad8b277e886aa87e287ada5e9f3cbe3
